import type { Metadata } from "next";
import "./globals.css";
import Cabecalho from "@/componentes/Cabecalho/Cabecalho";
import Rodape from "@/componentes/Rodape/Rodape";


export const metadata: Metadata = {
  title: "SmartEnergy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
